# Generated by Django 5.0.2 on 2024-03-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedCharacters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=255)),
                ("user_password", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zipcode", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CachedComics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("character_id", models.IntegerField()),
                (
                    "character_id2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.cachedcharacters",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=255)),
                ("time_date", models.DateTimeField()),
                ("comment", models.TextField()),
                ("comm_time_date", models.DateTimeField()),
                (
                    "fKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.users"
                    ),
                ),
            ],
        ),
    ]
