# Generated by Django 5.0.2 on 2024-03-01 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forumcomments",
            old_name="fKey",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="forumcomments",
            name="user_name",
        ),
        migrations.CreateModel(
            name="Bookmarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=500)),
                ("creationDate", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.users"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="CachedCharacters",
            new_name="Characters",
        ),
        migrations.CreateModel(
            name="ComicCharacters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.characters",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("publicationDate", models.DateField()),
                ("summary", models.TextField()),
                ("linkForPurchase", models.CharField(max_length=500)),
                (
                    "characters",
                    models.ManyToManyField(
                        through="pages.ComicCharacters", to="pages.characters"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comiccharacters",
            name="comic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.comics"
            ),
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("reviewDate", models.DateField()),
                ("body", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "comic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.comics"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.users"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CachedComics",
        ),
    ]
