# Generated by Django 5.0.2 on 2024-04-13 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_savesearch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="user_password",
        ),
    ]
