# Generated by Django 5.0.2 on 2024-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_characters_characterdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='comicIMG',
            field=models.TextField(default='image'),
        ),
    ]
