# Generated by Django 5.0.2 on 2024-04-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_comics_comicid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comics',
            name='publicationDate',
        ),
        migrations.AddField(
            model_name='comics',
            name='comicYear',
            field=models.IntegerField(default=1),
        ),
    ]
