# Generated by Django 5.0.2 on 2024-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_comics_publicationdate_comics_comicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='comicYear',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
