# Generated by Django 5.0.2 on 2024-04-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_comics_comicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='characters',
            field=models.ManyToManyField(related_name='CharComic', through='pages.ComicCharacters', to='pages.characters'),
        ),
    ]
