# Generated by Django 5.0.2 on 2024-05-01 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_comics_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comics',
            name='characters',
        ),
        migrations.AddField(
            model_name='comics',
            name='characters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.characters'),
        ),
    ]
