# Generated by Django 5.0.2 on 2024-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_comics_characters_comics_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='summary',
            field=models.TextField(default='This character has no description'),
        ),
    ]
