# Generated by Django 5.0.2 on 2024-05-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_comics_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='characterAppearances',
            field=models.TextField(default='These characters show up'),
        ),
        migrations.AddField(
            model_name='comics',
            name='comicAuthors',
            field=models.TextField(default='Authors'),
        ),
    ]
